package com.pixeleyes;

/** Встроенные глаза. Файл собирается из eyes/skins скриптом tools/gen_builtins.py, руками не править. */
final class Builtins {

    static final int DEFAULT = 0;

    static final String[] JSON = {
            "{\"format\":1,\"id\":\"cartoon\",\"name\":\"Мультяшные\",\"author\":\"@van1lLove\",\"description\":\"Круглые белые глаза с чёрным зрачком, как в мультике\",\"tags\":[\"милые\",\"классика\"],\"palette\":{\"#\":\"#1b1b22\",\"w\":\"#ffffff\",\"s\":\"#dfe3ee\",\"p\":\"#15151c\",\"h\":\"#ffffff\"},\"eye\":[\"....####....\",\"..##wwww##..\",\".#wwwwwwww#.\",\".#wwwwwwww#.\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\".#swwwwwws#.\",\".#sswwwwss#.\",\"..##ssss##..\",\"....####....\"],\"sclera\":\"ws\",\"iris\":[\".pp.\",\"pppp\",\"pppp\",\".pp.\"],\"pupil\":\"p\",\"highlight\":[\"h\"],\"highlight_offset\":[-1,-1],\"lid\":\"#cfd5e3\",\"lash\":\"#1b1b22\",\"travel\":[3,3],\"layout\":{\"count\":2,\"gap\":3,\"mirror\":true},\"behavior\":{\"blink\":[2.5,6],\"style\":\"smooth\",\"stare\":0.15}}",
            "{\"format\":1,\"id\":\"cartoon_pink\",\"name\":\"Конфетка\",\"description\":\"Мультяшные глаза с яркой розовой радужкой\",\"tags\":[\"милые\"],\"palette\":{\"#\":\"#2b1630\",\"w\":\"#ffffff\",\"s\":\"#f1e4f2\",\"a\":\"#e0479e\",\"b\":\"#ff8cc6\",\"p\":\"#2b1630\",\"h\":\"#ffffff\"},\"eye\":[\"....####....\",\"..##wwww##..\",\".#wwwwwwww#.\",\".#wwwwwwww#.\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\".#swwwwwws#.\",\".#sswwwwss#.\",\"..##ssss##..\",\"....####....\"],\"sclera\":\"ws\",\"iris\":[\".aaaa.\",\"aabbaa\",\"abppba\",\"abppba\",\"aabbaa\",\".aaaa.\"],\"pupil\":\"p\",\"highlight\":[\"hh\",\"h.\"],\"highlight_offset\":[-1,-1],\"lid\":\"#ffd3e2\",\"lash\":\"#2b1630\",\"travel\":[3,3],\"layout\":{\"count\":2,\"gap\":3,\"mirror\":true},\"behavior\":{\"blink\":[2,5],\"style\":\"smooth\",\"stare\":0.25,\"speed\":1.1},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"anime\",\"name\":\"Аниме\",\"author\":\"@van1lLove\",\"description\":\"Большие блестящие глаза с фиолетовой радужкой и ресницами\",\"tags\":[\"милые\",\"аниме\"],\"palette\":{\"#\":\"#241532\",\"l\":\"#3b2152\",\"w\":\"#ffffff\",\"s\":\"#e6defa\",\"a\":\"#4a227f\",\"b\":\"#7a45d6\",\"c\":\"#b88cff\",\"d\":\"#e2ccff\",\"p\":\"#170b26\",\"h\":\"#ffffff\"},\"eye\":[\"....#########..\",\"#.###########.#\",\".##wwwwwwwwwww#\",\"#wwwwwwwwwwwww#\",\"#wwwwwwwwwwwww#\",\"#wwwwwwwwwwwww#\",\"#wwwwwwwwwwwww#\",\"#wwwwwwwwwwwww#\",\".lwwwwwwwwwwwl.\",\".lswwwwwwwwwsl.\",\"..llsswwwssll..\",\"....lllllll....\"],\"sclera\":\"ws\",\"iris\":[\"..aaaa..\",\".aaaaaa.\",\"aaappaaa\",\"abpppppb\",\"bbpppppb\",\"bbbpppbb\",\"bcbbbbcb\",\".cdddcc.\",\"..dddd..\"],\"iris_offset\":[0,1],\"pupil\":\"p\",\"highlight\":[\"hh...\",\"hh...\",\".....\",\"....h\"],\"highlight_offset\":[-1,-2],\"lid\":\"#f9d9cf\",\"lash\":\"#241532\",\"travel\":[2,1],\"layout\":{\"count\":2,\"gap\":4,\"mirror\":true},\"frames\":{\"closed\":[\"...............\",\"...............\",\"...............\",\"...............\",\"...............\",\"...............\",\"#.............#\",\".##.........##.\",\"...##.....##...\",\".....#####.....\",\"...............\",\"...............\"],\"happy\":[\"...............\",\"...............\",\"...............\",\"...............\",\"......###......\",\"....##...##....\",\"...#.......#...\",\"..#.........#..\",\".#...........#.\",\"...............\",\"...............\",\"...............\"]},\"behavior\":{\"blink\":[2,5],\"style\":\"smooth\",\"stare\":0.25,\"speed\":1.1}}",
            "{\"format\":1,\"id\":\"kawaii\",\"name\":\"Кавай\",\"description\":\"Тёмные чиби-глаза с большими бликами и розовым отсветом\",\"tags\":[\"милые\",\"аниме\"],\"palette\":{\"#\":\"#1a0f24\",\"d\":\"#3d2257\",\"e\":\"#55306f\",\"m\":\"#ff7ab8\",\"q\":\"#ffc2de\",\"h\":\"#ffffff\"},\"eye\":[\"...####...\",\".##dddd##.\",\".#dddddd#.\",\"#dddddddd#\",\"#dddddddd#\",\"#dddddddd#\",\"#dddddddd#\",\"#deeeeeed#\",\"#eeeeeeee#\",\".#eeeeee#.\",\".##eeee##.\",\"...####...\"],\"sclera\":\"de\",\"iris\":[\".mm.\",\"mqqm\",\".mm.\"],\"iris_offset\":[0,2],\"highlight\":[\"hhh..\",\"hhh..\",\"hhh..\",\".....\",\"...h.\"],\"highlight_offset\":[-1,-4],\"lid\":\"#f9d9cf\",\"lash\":\"#1a0f24\",\"travel\":[2,2],\"layout\":{\"count\":2,\"gap\":4,\"mirror\":true},\"frames\":{\"happy\":[\"..........\",\"..........\",\"..........\",\"....##....\",\"...####...\",\"..##..##..\",\".##....##.\",\".#......#.\",\"..........\",\"..........\",\"..........\",\"..........\"],\"closed\":[\"..........\",\"..........\",\"..........\",\"..........\",\"..........\",\"..........\",\".#......#.\",\".##....##.\",\"..######..\",\"..........\",\"..........\",\"..........\"]},\"behavior\":{\"blink\":[2,5],\"style\":\"smooth\",\"stare\":0.3,\"speed\":1.1},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"cat\",\"name\":\"Котик\",\"description\":\"Жёлто-зелёные кошачьи глаза с вертикальным зрачком\",\"tags\":[\"милые\",\"животные\"],\"palette\":{\"#\":\"#1c1a14\",\"w\":\"#d6ee5f\",\"g\":\"#a4c93c\",\"p\":\"#121212\",\"h\":\"#ffffff\"},\"eye\":[\"....######....\",\"..##gggggg##..\",\".#gwwwwwwwwg#.\",\"#gwwwwwwwwwwg#\",\"#wwwwwwwwwwww#\",\"#gwwwwwwwwwwg#\",\".#gwwwwwwwwg#.\",\"..##gggggg##..\",\"....######....\"],\"sclera\":\"wg\",\"iris\":[\".p.\",\".p.\",\"ppp\",\"ppp\",\"ppp\",\".p.\",\".p.\"],\"pupil\":\"p\",\"highlight\":[\"hh\",\"h.\"],\"highlight_offset\":[-3,-2],\"highlight_fixed\":true,\"lid\":\"#4a4038\",\"lash\":\"#121212\",\"travel\":[3,1],\"layout\":{\"count\":2,\"gap\":4,\"mirror\":true},\"behavior\":{\"blink\":[3,8],\"style\":\"smooth\",\"stare\":0.35,\"speed\":1.3},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"retro\",\"name\":\"Ретро\",\"description\":\"Чёрные овалы с бликом, как в старых 8-битных играх\",\"tags\":[\"милые\",\"ретро\"],\"palette\":{\"k\":\"#101010\",\"h\":\"#ffffff\"},\"eye\":[\".kkkk.\",\"kkkkkk\",\"kkkkkk\",\"kkkkkk\",\"kkkkkk\",\"kkkkkk\",\"kkkkkk\",\"kkkkkk\",\"kkkkkk\",\".kkkk.\"],\"sclera\":\"k\",\"iris\":[\"hh\",\"hh\",\"h.\"],\"iris_offset\":[0,-2],\"lid\":\"none\",\"lash\":\"#101010\",\"travel\":[1,2],\"layout\":{\"count\":2,\"gap\":4,\"mirror\":true},\"behavior\":{\"blink\":[2.5,6],\"style\":\"snap\",\"stare\":0.2},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"robot\",\"name\":\"Робот\",\"description\":\"Светодиодные глаза на тёмной панели\",\"tags\":[\"милые\",\"техника\"],\"palette\":{\"#\":\"#4b5363\",\"k\":\"#0a0f14\",\"c\":\"#33e6ff\",\"C\":\"#c9fbff\",\"r\":\"#ff4f8b\"},\"eye\":[\"############\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"############\"],\"sclera\":\"k\",\"iris\":[\"cccc\",\"cCCc\",\"cCCc\",\"cccc\"],\"lid\":\"#0a0f14\",\"lash\":\"#1f7f8c\",\"travel\":[3,2],\"layout\":{\"count\":2,\"gap\":3,\"mirror\":true},\"frames\":{\"closed\":[\"############\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kcccccccck#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"############\"],\"happy\":[\"############\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkcckkkk#\",\"#kkkckkckkk#\",\"#kkckkkkckk#\",\"#kckkkkkkck#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"############\"],\"love\":[\"############\",\"#kkkkkkkkkk#\",\"#kkrrkkrrkk#\",\"#krrrrrrrrk#\",\"#krrrrrrrrk#\",\"#kkrrrrrrkk#\",\"#kkkrrrrkkk#\",\"#kkkkrrkkkk#\",\"#kkkkkkkkkk#\",\"############\"]},\"behavior\":{\"blink\":[3,8],\"style\":\"snap\",\"stare\":0.2,\"speed\":1.4},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"sleepy\",\"name\":\"Сонные\",\"description\":\"Тяжёлые веки, медленный взгляд, всегда хотят спать\",\"tags\":[\"забавные\"],\"palette\":{\"#\":\"#2a1d14\",\"w\":\"#fbf6ef\",\"b\":\"#8a5a36\",\"p\":\"#2a170c\",\"h\":\"#ffffff\"},\"eye\":[\"...######...\",\".##wwwwww##.\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\".#wwwwwwww#.\",\"..##wwww##..\",\"....####....\"],\"sclera\":\"w\",\"iris\":[\".bb.\",\"bppb\",\"bppb\",\".bb.\"],\"pupil\":\"p\",\"highlight\":[\"h\"],\"highlight_offset\":[-1,-1],\"lid\":\"#e8c4a8\",\"lash\":\"#5a3a26\",\"travel\":[3,2],\"layout\":{\"count\":2,\"gap\":3,\"mirror\":true},\"behavior\":{\"blink\":[3,7],\"style\":\"smooth\",\"speed\":0.55,\"open\":0.5,\"stare\":0.2},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"grumpy\",\"name\":\"Злюка\",\"description\":\"Насупленные брови и красная радужка, всем недоволен\",\"tags\":[\"забавные\"],\"palette\":{\"#\":\"#1f1410\",\"w\":\"#f6efe6\",\"r\":\"#b3261e\",\"p\":\"#1a0b08\",\"h\":\"#ffffff\"},\"eye\":[\"##..........\",\".####.......\",\"...#####....\",\".....####...\",\"..########..\",\".#wwwwwwww#.\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\"#wwwwwwwwww#\",\".#wwwwwwww#.\",\"..########..\"],\"sclera\":\"w\",\"iris\":[\".rr.\",\"rppr\",\"rppr\",\".rr.\"],\"pupil\":\"p\",\"highlight\":[\"h\"],\"highlight_offset\":[-1,-1],\"lid\":\"#9c7a6a\",\"lash\":\"#2a1a14\",\"travel\":[3,1],\"layout\":{\"count\":2,\"gap\":2,\"mirror\":true},\"behavior\":{\"blink\":[3,7],\"style\":\"snap\",\"slant\":0.35,\"open\":0.85,\"stare\":0.4},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"demon\",\"name\":\"Демон\",\"description\":\"Красное яблоко и жёлтый змеиный зрачок\",\"tags\":[\"жуткие\"],\"palette\":{\"#\":\"#0d0405\",\"r\":\"#8f0f17\",\"v\":\"#5c0a10\",\"y\":\"#ffcc1f\",\"o\":\"#0d0405\"},\"eye\":[\"....#####....\",\"..##rrrrr##..\",\".#rrvrrrrrr#.\",\"#rrrrrrrvrrr#\",\"#rrrrrrrrrrr#\",\"#rrvrrrrrrrr#\",\".#rrrrrrvrr#.\",\"..##rrrrr##..\",\"....#####....\"],\"sclera\":\"rv\",\"iris\":[\".y.\",\"yoy\",\"yoy\",\"yoy\",\"yoy\",\".y.\"],\"pupil\":\"o\",\"lid\":\"#3a0a0e\",\"lash\":\"#0d0405\",\"travel\":[3,1],\"layout\":{\"count\":2,\"gap\":3,\"mirror\":true},\"behavior\":{\"blink\":[4,10],\"style\":\"snap\",\"slant\":0.35,\"stare\":0.5,\"creepy\":true,\"speed\":1.2},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"bloodshot\",\"name\":\"Налитые кровью\",\"description\":\"Красные прожилки, маленький зрачок, дёргаются и почти не моргают\",\"tags\":[\"жуткие\"],\"palette\":{\"#\":\"#3a2a22\",\"w\":\"#efe7d6\",\"v\":\"#c2272d\",\"u\":\"#8c1a1f\",\"i\":\"#6b1d15\",\"p\":\"#0a0505\"},\"eye\":[\".....####.....\",\"...##wwww##...\",\"..#vwwwwwwu#..\",\".#wwvwwwwvww#.\",\".#vwwwwwwwwv#.\",\"#wvwwwwwwwwww#\",\"#uwwwwwwwwwvv#\",\"#vvwwwwwwwwwu#\",\"#wwwwwwwwwwvw#\",\".#wvwwwwwwwu#.\",\".#vwwwwwwvvw#.\",\"..##wwwvww##..\",\"....######....\"],\"sclera\":\"wvu\",\"iris\":[\".ii.\",\"ippi\",\"ippi\",\".ii.\"],\"pupil\":\"p\",\"lid\":\"#b89a8a\",\"lash\":\"#3a1a14\",\"travel\":[4,3],\"layout\":{\"count\":2,\"gap\":3,\"mirror\":true},\"behavior\":{\"blink\":[6,14],\"style\":\"twitch\",\"twitch\":0.7,\"stare\":0.6,\"creepy\":true,\"speed\":1.6},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"void\",\"name\":\"Пустота\",\"description\":\"Чёрные глаза с крошечным белым зрачком, медленно следят и не моргают\",\"tags\":[\"жуткие\"],\"palette\":{\"#\":\"#3d0c0c\",\"k\":\"#050506\",\"g\":\"#6b6b70\",\"h\":\"#ffffff\"},\"eye\":[\"...######...\",\".##kkkkkk##.\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\"#kkkkkkkkkk#\",\".##kkkkkk##.\",\"...######...\"],\"sclera\":\"k\",\"iris\":[\".g.\",\"ghg\",\".g.\"],\"pupil\":\"h\",\"lid\":\"#050506\",\"lash\":\"#3d0c0c\",\"travel\":[3,2],\"layout\":{\"count\":2,\"gap\":3,\"mirror\":true},\"behavior\":{\"blink\":[0,0],\"style\":\"smooth\",\"speed\":0.45,\"stare\":0.8,\"creepy\":true},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"cyclops\",\"name\":\"Циклоп\",\"description\":\"Один большой глаз с прожилками и змеиным зрачком\",\"tags\":[\"жуткие\"],\"palette\":{\"#\":\"#2a1d18\",\"w\":\"#f2ead8\",\"v\":\"#c23a3a\",\"g\":\"#5f8a1a\",\"y\":\"#c9e64a\",\"p\":\"#0c0c0c\",\"h\":\"#ffffff\"},\"eye\":[\"......########......\",\"....##wwwwwwww##....\",\"..##wvvwwwwwwwww##..\",\".#wvwwwwwwwwwwwvww#.\",\".#wwwwwwwwwwwwwwww#.\",\"#wvvwwwwwwwwwwwwwvw#\",\"#wwwwwwwwwwwwwwwvww#\",\"#wwwwwwwwwwwwwwwwww#\",\"#wvwwwwwwwwwwwwwwvw#\",\".#wwvwwwwwwwwwwvww#.\",\".#wwwwwwwwwwwwvwww#.\",\"..##wwvwwwwwwvww##..\",\"....##wwwwwwww##....\",\"......########......\"],\"sclera\":\"wv\",\"iris\":[\"..gg..\",\".gyyg.\",\"gyppyg\",\"gyppyg\",\"gyppyg\",\"gyppyg\",\".gyyg.\",\"..gg..\"],\"pupil\":\"p\",\"highlight\":[\"h\"],\"highlight_offset\":[-4,-3],\"highlight_fixed\":true,\"lid\":\"#8c6e5e\",\"lash\":\"#2a1810\",\"travel\":[5,3],\"layout\":{\"count\":1},\"behavior\":{\"blink\":[4,10],\"style\":\"snap\",\"twitch\":0.3,\"stare\":0.5,\"creepy\":true,\"speed\":1.2},\"author\":\"@van1lLove\"}",
            "{\"format\":1,\"id\":\"swarm\",\"name\":\"Рой\",\"description\":\"Семь глаз разного размера, каждый смотрит и моргает сам по себе\",\"tags\":[\"жуткие\"],\"palette\":{\"#\":\"#2a1f1f\",\"w\":\"#e8e0d0\",\"v\":\"#b8423a\",\"p\":\"#3a0d0d\"},\"eye\":[\"..####..\",\".#wwww#.\",\"#wwwwww#\",\"#wvwwww#\",\".#wwww#.\",\"..####..\"],\"sclera\":\"wv\",\"iris\":[\"pp\",\"pp\"],\"pupil\":\"p\",\"lid\":\"#9c7f72\",\"lash\":\"#2a1f1f\",\"travel\":[2,1],\"layout\":{\"eyes\":[{\"x\":13,\"y\":5,\"scale\":2},{\"x\":0,\"y\":3},{\"x\":3,\"y\":13,\"mirror\":true},{\"x\":31,\"y\":0,\"mirror\":true},{\"x\":32,\"y\":11},{\"x\":20,\"y\":0},{\"x\":6,\"y\":0}]},\"behavior\":{\"blink\":[1.5,7],\"style\":\"snap\",\"twitch\":0.4,\"stare\":0.3,\"independent\":true,\"creepy\":true},\"author\":\"@van1lLove\"}",
    };

    private Builtins() {
    }
}
